# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
